# Generated by Django 6.0.7 on 2026-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hs_code', models.CharField(help_text='Harmonized System Code for Customs Tariff', max_length=20)),
                ('unit_weight_kg', models.DecimalField(decimal_places=3, help_text='Net weight per unit in kg', max_digits=8)),
                ('dimensions_cm', models.CharField(blank=True, max_length=50, null=True)),
                ('packages_count', models.IntegerField(default=1, help_text='Default number of outer packages/cartons')),
            ],
        ),
    ]
