# Generated by Django 6.0.7 on 2026-09-09 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0020_quotation_currency_quotation_incoterm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier_name', models.CharField(help_text='e.g. DHL Express, FedEx, Ocean Freight Carrier', max_length=255)),
                ('consignment_note_number', models.CharField(help_text='Air Waybill (AWB) or Bill of Lading (B/L) No.', max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sender_address', models.TextField()),
                ('consignee_address', models.TextField()),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_signature_data', models.TextField(blank=True, help_text='Base64 encoded PNG signature string', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='invoices.invoice')),
            ],
        ),
    ]
