# Generated by Django 6.0.7 on 2026-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_ref', models.CharField(max_length=50, unique=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=30, null=True)),
                ('office_number', models.CharField(blank=True, max_length=30, null=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('entity_address', models.TextField()),
                ('entity_postal_code', models.CharField(max_length=20)),
                ('incoterm', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_term', models.CharField(default='30 Days', max_length=50)),
                ('validity_of_quotation', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
