# Generated by Django 6.0.7 on 2026-08-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_catalogitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core_app.catalogitem')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
