# Generated by Django 6.0.7 on 2026-08-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_catalogpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
