# Generated by Django 6.0.7 on 2026-09-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_catalogitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog_photos/'),
        ),
    ]
