# Generated by Django 6.0.7 on 2026-09-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_companysettings_invoice_client_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='quotation_format',
            field=models.CharField(default='QT-{YYYY}-{SEQ}', max_length=100),
        ),
    ]
