# Generated by Django 6.0.7 on 2026-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_companysettings_quotation_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='quotation_ref_label',
            field=models.CharField(default='Quotation Reference', max_length=100),
        ),
    ]
