# Generated by Django 6.0.7 on 2026-09-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_companysettings_quotation_ref_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='branch_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='quotation_format',
            field=models.CharField(default='FMQ-{DDMMYY}/{CLIENT_NAME}/{SEQ}', max_length=100),
        ),
    ]
