# Generated by Django 6.0.7 on 2026-07-23 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
