# Generated by Django 6.0.7 on 2026-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='po_docs/'),
        ),
    ]
