# Generated by Django 6.0.7 on 2026-08-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_purchaseorder_supporting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='cost_centre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
