# Generated by Django 6.0.7 on 2026-08-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
