# Generated by Django 6.0.7 on 2026-09-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='branch_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
