# Generated by Django 6.0.7 on 2026-09-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_companysettings_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
