# Generated by Django 6.0.7 on 2026-08-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_catalogitem_is_deleted_invoice_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INV', 'Invoice'), ('PO', 'Purchase Order')], max_length=3)),
                ('year', models.PositiveIntegerField()),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('doc_type', 'year')},
            },
        ),
    ]
