# Generated by Django 6.0.7 on 2026-09-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_invoice_purchase_order_invoice_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='packing_dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
