# Generated by Django 6.0.7 on 2026-09-04 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_catalogitem_image'),
        ('invoices', '0018_catalogitem_gross_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTermTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('due_days', models.IntegerField(help_text='Number of days until full payment is due')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(help_text='Date until which this quoted price is valid')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('payment_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.paymenttermtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.catalogitem')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.quotation')),
            ],
        ),
    ]
