# Generated by Django 6.0.7 on 2026-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_paymenttermtemplate_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.CharField(default='SGD', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='incoterm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quote_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
