# Generated by Django 6.0.7 on 2026-09-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_quotation_currency_quotation_incoterm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='bank_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='branch_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
