# Generated by Django 6.0.7 on 2026-09-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_companysettings_bank_address_and_more'),
        ('invoices', '0021_companysettings_bank_address_and_more'),
    ]

    operations = [
    ]
